version: "2"

services:
  mysql:
    image: mysql:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_PASSWORD=123456
        - MYSQL_USER=test
    ports:
        - "127.0.0.1:3306:3306"
  redis:
    image: redis:3.2
    ports:
        - "127.0.0.1:6379:6379"
