version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yml", "--log-level=debug"]
    ports:
      - "55680:55680/tcp"
      - "55681:55681/tcp"
      - "55678:55678/tcp"
      - "14268:14268/tcp"
      - "4317:4317/tcp"
      - "9411:9411/tcp"
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
  python-microservice:
    build:
      context: python-microservice
      dockerfile: Dockerfile
    environment:
      # The spec says this should include http or https but python appears to have implemented differently
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:55680
      - OTEL_RESOURCE="deployment.enviroment=otel_sandbox,version=v1"
    depends_on:
      - otel-collector
      - node-microservice
      - mongo
  node-microservice:
    build:
      context: node-microservice
      dockerfile: Dockerfile
    environment:
      # opentelemetry-js only has json over http at this time 
      - OTEL_EXPORTER_OTLP_HTTP_ENDPOINT=otel-collector:55681
      - OTEL_RESOURCE="deployment.enviroment=otel_sandbox,version=v1"
    depends_on:
      - otel-collector
      - mongo
  vegeta:
    container_name: vegeta
    image: peterevans/vegeta
    command: sh -c "echo 'GET http://python-microservice:5000/' | vegeta attack -rate=1 -duration=15m"
    depends_on:
      - python-microservice      
  mongo:
    image: mongo:3.5
    container_name: mongo
    ports:
      - "27017:27017/tcp"
