version: '3'

services:
  mongodb:
    image: mongo:3.5
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./fava:/data/db

  datadog:
    image: datadog/docker-dd-agent
    environment:
      - DD_BIND_HOST=0.0.0.0
      - DD_API_KEY
    ports:
      - "127.0.0.1:8126:8126"
