version: "3.4"

services:

  agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - /proc/:/host/proc/:ro 
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro 
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      # - DD_LOG_LEVEL=debug

  laravel42_php56_apache:
    build:
      context: Laravel42
      dockerfile: Dockerfile_php56
    volumes:
      - ./Laravel42:/var/www/html
    ports:
      - 8042:80
    environment:
      DD_AGENT_HOST: agent
