version: "3.4"

services:

  agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_APM_ENABLED=true

  laravel42_php56_apache:
    build:
      context: .
      dockerfile: Dockerfile_laravel42_php56_apache
    volumes:
      - ./apache2.conf:/etc/apache2/apache2.conf
      - ./Laravel42:/var/www
      - ./Laravel42/public:/var/www/html
      - composer-cache:/root/.composer/cache
    depends_on:
      - agent
    ports:
      - 8042:80
    environment:
      DD_AGENT_HOST: agent
      ddtrace_app_name: some_app
      DD_DISTRIBUTED_TRACING: 'true'

volumes:
  composer-cache:
